title: Experimenta Teleco 
description: Una pagina web para experimentar las telecomunicaciones
theme: just-the-docs
#logo: "/assets/images/Logos Quantum Fracture.png"

url: https://just-the-docs.github.io

aux_links:
  Repository: https://github.com/CarmenGuidet/CarmenGuidet.github.io

compress_html:
  blanklines: true


