title: Experimenta Teleco
description: Una pagina web para experimentar las telecomunicaciones
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Repository: https://github.com/CarmenGuidet/CarmenGuidet.github.io

